### ISSUE TITLE
TightVNC not working

### ISSUE THREAD

**Issue by parxal** [T1T4N/NVNC#12]
TightVNC viewer connect's, but no image is showed :(

**Comment by henrywood** [comment]
Any hope of getting TightVNC (or any other viewer) working with NVNC ? I tried both TightVNC and RealVNC and none of them works. I also tried the codeplex version but the result were similar.

NVNC appears to be rather useless if common VNC Viewers just connects and shows a black screen ?

As it is stated that NVNC was tested with TightVNC, I wonder what settings (especially encoding) were used during these tests ?

**Comment by T1T4N** [comment]
Check the latest updates. Example settings for supported viewers are commited.
