### ISSUE TITLE
Unable to read data from the transport connection (Remmina)

### ISSUE THREAD

**Issue by henrywood** [T1T4N/NVNC#13]
When using Remmina from Linux, a black screen is shown in the viewer (Remmina) and it then closes the connection.
On the trace output of NVNC I see:

Started VNC Server at port: 5900
192.168.1.101
Wrote Protocol Version
Read Protocol Version
Awaiting Authentication
Authentication successfull !
Share: True
Server name: T!T@N-VNC
Read SetPixelFormat
Read SetEncodings
Read FrameBufferUpdateRequest
Read PointerEvent
Read PointerEvent
Read PointerEvent
Read PointerEvent
Read PointerEvent
Unable to read beyond the end of the stream.
Read SetPixelFormat
Unable to read data from the transport connection: A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.

Also, after any exception in NVNC it is impossible to make new connections to NVNC.

NVNC needs to be restarted...

**Comment by D4n13l3k00** [comment]
I've got this problem too :(
