### ISSUE TITLE
OutOfRange at CopyPixels

### ISSUE THREAD

**Issue by EmaX093** [T1T4N/NVNC#3]
Hi! My desktop has 1920x1080 screen resolution. I tried to run the example NVNC Example, but when it starts it throw this exception:

> System.IndexOutOfRangeException was unhandled
>  Message=Índice fuera de los límites de la matriz
>  Source=NVNC
>  StackTrace:
>       en NVNC.Utils.PixelGrabber.CopyPixels(Int32[] pixels, Int32 scanline, Int32 x, Int32 y, Int32 w,  Int32 h) en c:\Users\Emanuel\Documents\GitHub\NVNC\NVNC\Utils\PixelGrabber.cs:línea 420
>       en NVNC.Utils.ScreenTree.QuadNode.GenerateChildren() en  c:\Users\Emanuel\Documents\GitHub\NVNC\NVNC\Utils\ScreenTree\QuadNode.cs:línea 240
>       en NVNC.Utils.ScreenTree.QuadNode..ctor(Rectangle2 bounds, Int32[] data) en c:\Users\Emanuel\Documents\GitHub\NVNC\NVNC\Utils\ScreenTree\QuadNode.cs:línea 35
>       en NVNC.Utils.ScreenTree.QuadTree.BFSLowest() en c:\Users\Emanuel\Documents\GitHub\NVNC\NVNC\Utils\ScreenTree\QuadTree.cs:línea 121
>       en NVNC.Utils.ScreenTree.QuadTree..ctor(Rectangle2 screenSize, Int32[] pixels, Int32 minTileHeight, Int32 minTileWidth) en c:\Users\Emanuel\Documents\GitHub\NVNC\NVNC\Utils\ScreenTree\QuadTree.cs:línea 32
>       en NVNC.Utils.ScreenHandler..ctor(Rectangle screen, Boolean hashOnlyCompare) en c:\Users\Emanuel\Documents\GitHub\NVNC\NVNC\Utils\ScreenHandler.cs:línea 40
>       en NVNC.VncServer.Start() en c:\Users\Emanuel\Documents\GitHub\NVNC\NVNC\VncServer.cs:línea 81
>       en VNCTest.Program.Main(String[] args) en c:\Users\Emanuel\Documents\GitHub\NVNC\NVNC Example\Program.cs:línea 15
>       en System.AppDomain._nExecuteAssembly(Assembly assembly, String[] args)
>       en System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
>       en Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
>       en System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>       en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>      en System.Threading.ThreadHelper.ThreadStart()
>   InnerException: 

Here you have a screenshot.

![ior](https://cloud.githubusercontent.com/assets/9728617/10471286/c2f5cbb0-71ea-11e5-9eb4-316349eb4589.png)

Cheers!

**Comment by EmaX093** [comment]
#1 Sorry, i didn't see this. I'm closing the issue.

**Comment by suifengshiqu** [comment]
Hi,can you tell me how to solve this problem?

**Comment by tqtxwysse** [comment]
多线程导致的问题，内存应该加锁
