### ISSUE TITLE
realVNC Viewer not working with T1T4N VNC server

### ISSUE THREAD

**Issue by BilalRabbani** [T1T4N/NVNC#9]
T1T4N is working with tightVNC but not working with realVNC. realVNC Viewer crashes when connect to T1T4N VNC server. How to make realVNC Viewer work.

Regards

**Comment by 0xFireball** [comment]
Have tested. Can confirm.

**Comment by 81867376** [comment]
System.IndexOutOfRangeException ， At    **return ourPixels;**  

 public static int[] CopyPixels(int[] pixels, int scanline, int x, int y, int w, int h)
        {
            int size = w * h;
            int[] ourPixels = new int[size];
            int jump = scanline - w;
            int s = 0;
            int p = y * scanline + x;
            Trace.WriteLine("Data offset: " + p);
            for (int i = 0; i < size; i++, s++, p++)
            {
                if (s == w)
                {
                    s = 0;
                    p += jump;
                }
                ourPixels[i] = pixels[p];
            }
            Trace.WriteLine("Data end: " + --p);
            return ourPixels;
        }

**Comment by tino-kuptz** [comment]
I know, very old, but for further references - fixed the exception above with switching from "Debug / Mixed" to "Debug / x86"
